DELETE FROM task;
DELETE FROM student;

INSERT INTO student(id, username, is_active, unique_url)
VALUES (1, 'v.zadov', 1, 'eOyjOZb9eIfULKMmGczVdCQvAuCnYw0BFVpc8os2QUtn7j4Ow4fiGJX1svOtJuGDOGkcHx'),
       (2, 'p.pastushenko', 1, 'iODbI4gffgZgALeVJSm2CiRef34ViRz1Xq2BtWazjREfq557LowecSt6mabynGM2zWm2o6'),
       (3, 't.kombat', 1, '6ct6iJZACWZA85J9tzBTbV93tFZrq0xQWTYURDdYNmIlnSS6LYfc0Aav8l8kVYqvebVdOW'),
       (4, 'n.zadova', 1, '26z97fO8jaiGuKKI5mmkHW5pWKEbGlS2agkIR8GygOOyG2EeBZOnOb2gBXK97UvKONcXn0'),
       (5, 's.smorkovich', 0, 'p4KRIPI7QhF21yCS6N1IeNj7sdzKGWTmpkpGLPKs4QGurtdWCmfCRRueCSvNsJazTZMnym');

INSERT INTO task(student_id, is_completed, content, completion_timestamp)
VALUES (1, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (1, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (1, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (1, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (2, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (3, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (4, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (4, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (4, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (4, 0, 'SCRAPED TABOEBA SENTENCE', NULL),
       (5, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (5, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (5, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (5, 1, 'SCRAPED TABOEBA SENTENCE', NULL),
       (5, 1, 'SCRAPED TABOEBA SENTENCE', NULL);